//
// CodeTemplatesDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class CodeTemplatesDto: Codable, JSONEncodable, Hashable {

    static let totalRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var templates: [CodeTemplateDto]
    public var total: Int

    public init(templates: [CodeTemplateDto], total: Int) {
        self.templates = templates
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case templates
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(templates, forKey: .templates)
        try container.encode(total, forKey: .total)
    }

    public static func == (lhs: CodeTemplatesDto, rhs: CodeTemplatesDto) -> Bool {
        lhs.templates == rhs.templates &&
        lhs.total == rhs.total
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(templates.hashValue)
        hasher.combine(total.hashValue)
        
    }
}

