//
// CodesDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class CodesDto: Codable, JSONEncodable, Hashable {

    static let totalRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var codes: [CodeDto]
    public var total: Int

    public init(codes: [CodeDto], total: Int) {
        self.codes = codes
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case codes
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(codes, forKey: .codes)
        try container.encode(total, forKey: .total)
    }

    public static func == (lhs: CodesDto, rhs: CodesDto) -> Bool {
        lhs.codes == rhs.codes &&
        lhs.total == rhs.total
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(codes.hashValue)
        hasher.combine(total.hashValue)
        
    }
}

