//
// CreateCustomerPresetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class CreateCustomerPresetDto: Codable, JSONEncodable, Hashable {

    public enum Platform: String, Codable, CaseIterable {
        case android = "ANDROID"
        case ios = "IOS"
        case web = "WEB"
    }
    public var platform: Platform

    public init(platform: Platform) {
        self.platform = platform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platform, forKey: .platform)
    }

    public static func == (lhs: CreateCustomerPresetDto, rhs: CreateCustomerPresetDto) -> Bool {
        lhs.platform == rhs.platform
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(platform.hashValue)
        
    }
}

