//
// CreateCodeDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class CreateCodeDto: Codable, JSONEncodable, Hashable {

    public var value: String
    public var templateId: UUID
    public var payload: AnyCodable

    public init(value: String, templateId: UUID, payload: AnyCodable) {
        self.value = value
        self.templateId = templateId
        self.payload = payload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case templateId
        case payload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(templateId, forKey: .templateId)
        try container.encode(payload, forKey: .payload)
    }

    public static func == (lhs: CreateCodeDto, rhs: CreateCodeDto) -> Bool {
        lhs.value == rhs.value &&
        lhs.templateId == rhs.templateId &&
        lhs.payload == rhs.payload
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(value.hashValue)
        hasher.combine(templateId.hashValue)
        hasher.combine(payload.hashValue)
        
    }
}

