//
// RedeemCodeRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class RedeemCodeRequestDto: Codable, JSONEncodable, Hashable {

    public enum Platform: String, Codable, CaseIterable {
        case android = "ANDROID"
        case ios = "IOS"
        case web = "WEB"
    }
    public var codeValue: String
    public var platform: Platform?

    public init(codeValue: String, platform: Platform? = nil) {
        self.codeValue = codeValue
        self.platform = platform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case codeValue
        case platform
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(codeValue, forKey: .codeValue)
        try container.encodeIfPresent(platform, forKey: .platform)
    }

    public static func == (lhs: RedeemCodeRequestDto, rhs: RedeemCodeRequestDto) -> Bool {
        lhs.codeValue == rhs.codeValue &&
        lhs.platform == rhs.platform
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(codeValue.hashValue)
        hasher.combine(platform?.hashValue)
        
    }
}

