//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class AuthAPI {

    /**

     - parameter sdkAuthResuestPayload: (body)  
     - returns: AuthResponsePayload
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func authControllerSignInViaSdk(sdkAuthResuestPayload: SdkAuthResuestPayload) async throws -> AuthResponsePayload {
        return try await authControllerSignInViaSdkWithRequestBuilder(sdkAuthResuestPayload: sdkAuthResuestPayload).execute().body
    }

    /**
     - POST /auth/sdk
     - parameter sdkAuthResuestPayload: (body)  
     - returns: RequestBuilder<AuthResponsePayload> 
     */
    internal class func authControllerSignInViaSdkWithRequestBuilder(sdkAuthResuestPayload: SdkAuthResuestPayload) -> RequestBuilder<AuthResponsePayload> {
        let localVariablePath = "/auth/sdk"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sdkAuthResuestPayload)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AuthResponsePayload>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
