//
// CodeTemplatesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CodeTemplatesAPI {

    /**

     - parameter limit: (query)  
     - parameter offset: (query)  
     - returns: CodeTemplatesDto
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func codeTemplatesControllerGetMany(limit: Double, offset: Double) async throws -> CodeTemplatesDto {
        return try await codeTemplatesControllerGetManyWithRequestBuilder(limit: limit, offset: offset).execute().body
    }

    /**
     - GET /code-templates
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter limit: (query)  
     - parameter offset: (query)  
     - returns: RequestBuilder<CodeTemplatesDto> 
     */
    internal class func codeTemplatesControllerGetManyWithRequestBuilder(limit: Double, offset: Double) -> RequestBuilder<CodeTemplatesDto> {
        let localVariablePath = "/code-templates"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CodeTemplatesDto>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path)  
     - returns: CodeTemplateDto
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func codeTemplatesControllerGetOne(id: String) async throws -> CodeTemplateDto {
        return try await codeTemplatesControllerGetOneWithRequestBuilder(id: id).execute().body
    }

    /**
     - GET /code-templates/{id}
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter id: (path)  
     - returns: RequestBuilder<CodeTemplateDto> 
     */
    internal class func codeTemplatesControllerGetOneWithRequestBuilder(id: String) -> RequestBuilder<CodeTemplateDto> {
        var localVariablePath = "/code-templates/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CodeTemplateDto>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
