//
// CodesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal class CodesAPI {

    /**

     - parameter createCodeRequestDto: (body)  
     - returns: CodeDto
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func codesControllerCreate(createCodeRequestDto: CreateCodeRequestDto) async throws -> CodeDto {
        return try await codesControllerCreateWithRequestBuilder(createCodeRequestDto: createCodeRequestDto).execute().body
    }

    /**
     - POST /codes
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter createCodeRequestDto: (body)  
     - returns: RequestBuilder<CodeDto> 
     */
    internal class func codesControllerCreateWithRequestBuilder(createCodeRequestDto: CreateCodeRequestDto) -> RequestBuilder<CodeDto> {
        let localVariablePath = "/codes"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCodeRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CodeDto>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter createCodesRequestDto: (body)  
     - returns: [CodeDto]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func codesControllerCreateMany(createCodesRequestDto: CreateCodesRequestDto) async throws -> [CodeDto] {
        return try await codesControllerCreateManyWithRequestBuilder(createCodesRequestDto: createCodesRequestDto).execute().body
    }

    /**
     - POST /codes/batch
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter createCodesRequestDto: (body)  
     - returns: RequestBuilder<[CodeDto]> 
     */
    internal class func codesControllerCreateManyWithRequestBuilder(createCodesRequestDto: CreateCodesRequestDto) -> RequestBuilder<[CodeDto]> {
        let localVariablePath = "/codes/batch"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCodesRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[CodeDto]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter limit: (query)  
     - parameter offset: (query)  
     - returns: CodesDto
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func codesControllerGetOwn(limit: Int, offset: Int) async throws -> CodesDto {
        return try await codesControllerGetOwnWithRequestBuilder(limit: limit, offset: offset).execute().body
    }

    /**
     - GET /codes/me
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter limit: (query)  
     - parameter offset: (query)  
     - returns: RequestBuilder<CodesDto> 
     */
    internal class func codesControllerGetOwnWithRequestBuilder(limit: Int, offset: Int) -> RequestBuilder<CodesDto> {
        let localVariablePath = "/codes/me"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CodesDto>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter limit: (query)  
     - parameter offset: (query)  
     - parameter from: (query)  
     - parameter to: (query)  
     - parameter codeValue: (query)  (optional)
     - parameter redeemerId: (query)  (optional)
     - returns: CodeRedeemsDto
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func codesControllerGetRedeems(limit: Int, offset: Int, from: String, to: String, codeValue: String? = nil, redeemerId: UUID? = nil) async throws -> CodeRedeemsDto {
        return try await codesControllerGetRedeemsWithRequestBuilder(limit: limit, offset: offset, from: from, to: to, codeValue: codeValue, redeemerId: redeemerId).execute().body
    }

    /**
     - GET /codes/redeems
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter limit: (query)  
     - parameter offset: (query)  
     - parameter from: (query)  
     - parameter to: (query)  
     - parameter codeValue: (query)  (optional)
     - parameter redeemerId: (query)  (optional)
     - returns: RequestBuilder<CodeRedeemsDto> 
     */
    internal class func codesControllerGetRedeemsWithRequestBuilder(limit: Int, offset: Int, from: String, to: String, codeValue: String? = nil, redeemerId: UUID? = nil) -> RequestBuilder<CodeRedeemsDto> {
        let localVariablePath = "/codes/redeems"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "codeValue": (wrappedValue: codeValue?.encodeToJSON(), isExplode: true),
            "redeemerId": (wrappedValue: redeemerId?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CodeRedeemsDto>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter limit: (query)  
     - parameter offset: (query)  
     - parameter from: (query)  
     - parameter to: (query)  
     - returns: CodeRedeemsDto
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func codesControllerGetSelfRedeems(limit: Int, offset: Int, from: String, to: String) async throws -> CodeRedeemsDto {
        return try await codesControllerGetSelfRedeemsWithRequestBuilder(limit: limit, offset: offset, from: from, to: to).execute().body
    }

    /**
     - GET /codes/redeems/me
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter limit: (query)  
     - parameter offset: (query)  
     - parameter from: (query)  
     - parameter to: (query)  
     - returns: RequestBuilder<CodeRedeemsDto> 
     */
    internal class func codesControllerGetSelfRedeemsWithRequestBuilder(limit: Int, offset: Int, from: String, to: String) -> RequestBuilder<CodeRedeemsDto> {
        let localVariablePath = "/codes/redeems/me"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset.encodeToJSON(), isExplode: true),
            "from": (wrappedValue: from.encodeToJSON(), isExplode: true),
            "to": (wrappedValue: to.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CodeRedeemsDto>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter redeemCodeRequestDto: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    internal class func codesControllerRedeem(redeemCodeRequestDto: RedeemCodeRequestDto) async throws {
        return try await codesControllerRedeemWithRequestBuilder(redeemCodeRequestDto: redeemCodeRequestDto).execute().body
    }

    /**
     - POST /codes/redeem
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter redeemCodeRequestDto: (body)  
     - returns: RequestBuilder<Void> 
     */
    internal class func codesControllerRedeemWithRequestBuilder(redeemCodeRequestDto: RedeemCodeRequestDto) -> RequestBuilder<Void> {
        let localVariablePath = "/codes/redeem"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: redeemCodeRequestDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
